# Generated by Django 4.2.8 on 2024-07-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registered_date',
            field=models.DateTimeField(),
        ),
    ]
